create table person
(
id integer not null,
name varchar(255) not null,
location varchar(255),
birth_date timestamp,
primary key(id)
);


INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10001, 'SHIVAM', 'PUNE', CURRENT_TIMESTAMP);

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10002, 'DEVANAND', 'WANKHED', CURRENT_TIMESTAMP);

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10003, 'RAWANKAR', 'SHEGAON', CURRENT_TIMESTAMP);
